# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Hey Matter
version: "0.3.0"
slug: hey_matter
description: >-
  Simulates bridges to publish your Home Assistant entities to any
  Matter-compatible controller (Alexa, Apple Home, Google Home).
url: "https://github.com/sctale/hey-matter/tree/main/hey-matter"
arch:
  - armhf
  - aarch64
  - i386
  - amd64
init: false
ingress: true
panel_icon: mdi:bridge
panel_title: Hey Matter
startup: services
boot: auto
homeassistant_api: true
map:
  - config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(debug|info|warning|error)
  disable_log_colors: bool
  mdns_network_interface: str?
